# Configuration file for prek, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
# :schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.14.4"
hooks = [
  { id = "ruff", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "v0.0.10"
hooks = [
  { id = "ty" },
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-added-large-files" },
]
